version: "3.3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: instadevskill_image
    container_name: instaDevSkill
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - instadevskill-network

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: instadevskill-db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - instadevskill-network

  nginx:
    image: nginx:alpine
    container_name: instadevskill-nginx
    restart: unless-stopped
    ports:
      - 3500:80
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - instadevskill-network

volumes:
  db:
    driver: local

networks:
  instadevskill-network:
    driver: bridge
